### ISSUE TITLE
How to detect watermark

### ISSUE THREAD

**Issue by navdeep1604** [vladozc/watermarks#16]
I have 100 of images in jpg, png format, I just want to detect whether it has watermark or not. I would be thankful if you provide snippet using your code. I am confused. appreciate your help

**Comment by vladozc** [comment]
Hey Navdeep1604,

this library extracts least significant bit of each pixel in an image. It is either 0 or 1. If you then construct new image with these zeroes and ones, it may look like noise or it can represent an image (=> hidden watermark). However, there is no way library can determine if the result image is hidden watermark or not. You just have to look at the image and decide yourself.

Cheers,
Vlado
